<?php
return [
    'GET' => [
        '/' => ['HomeController', 'index'],
        '/login' => ['AuthController', 'showLogin'],
        '/register' => ['AuthController', 'showRegister'],
        '/logout' => ['AuthController', 'logout'],
        '/profile' => ['ProfileController', 'show'],
        '/restaurants' => ['RestaurantController', 'index'],
        '/restaurant' => ['RestaurantController', 'show'],
        '/menu-item' => ['MenuItemController', 'show'],
        '/food-experience' => ['FoodExperienceController', 'index'],
        '/food-experience/create' => ['FoodExperienceController', 'createForm'],
        '/food-experience/edit' => ['FoodExperienceController', 'editForm'],
        '/admin' => ['AdminController', 'dashboard'],
        '/admin/restaurants' => ['AdminController', 'restaurants'],
        '/admin/restaurants/create' => ['AdminController', 'restaurantCreateForm'],
        '/admin/restaurants/edit' => ['AdminController', 'restaurantEditForm'],
        '/admin/menu-items' => ['AdminController', 'menuItems'],
        '/admin/menu-items/create' => ['AdminController', 'menuItemCreateForm'],
        '/admin/menu-items/edit' => ['AdminController', 'menuItemEditForm'],
        '/admin/members' => ['AdminController', 'members'],
        '/admin/users/add' => ['AdminController', 'userAddForm'],
        '/admin/reviews' => ['AdminController', 'reviews'],
        '/admin/food-experience' => ['AdminController', 'foodExperienceAdmin'],
    ],
    'POST' => [
        '/login' => ['AuthController', 'login'],
        '/register' => ['AuthController', 'register'],
        '/profile' => ['ProfileController', 'update'],
        '/admin/restaurants/create' => ['AdminController', 'restaurantStore'],
        '/admin/restaurants/edit' => ['AdminController', 'restaurantUpdate'],
        '/admin/restaurants/delete' => ['AdminController', 'restaurantDelete'],
        '/admin/menu-items/create' => ['AdminController', 'menuItemStore'],
        '/admin/menu-items/edit' => ['AdminController', 'menuItemUpdate'],
        '/admin/menu-items/delete' => ['AdminController', 'menuItemDelete'],
        '/admin/users/add' => ['AdminController', 'userStore'],
        '/food-experience/create' => ['FoodExperienceController', 'store'],
        '/food-experience/edit' => ['FoodExperienceController', 'update'],
        '/food-experience/delete' => ['FoodExperienceController', 'deletePost'],
        '/api/reviews/add' => ['ApiController', 'reviewAdd'],
        '/api/restaurant-reviews/add' => ['ApiController', 'restaurantReviewAdd'],
        '/api/food-exp/comments/add' => ['ApiController', 'foodExpCommentAdd'],
        '/api/admin/member/delete' => ['AdminApiController', 'deleteMember'],
        '/api/admin/review/delete' => ['AdminApiController', 'deleteReview'],
        '/api/admin/food-post/delete' => ['AdminApiController', 'deleteFoodPost'],
        '/api/admin/food-comment/delete' => ['AdminApiController', 'deleteFoodComment'],
    ],
    'DELETE' => [
        '/api/reviews/delete' => ['ApiController', 'reviewDelete'],
        '/api/restaurant-reviews/delete' => ['ApiController', 'restaurantReviewDelete'],
        '/api/food-exp/comments/delete' => ['ApiController', 'foodExpCommentDelete'],
        '/api/food-exp/post/delete' => ['ApiController', 'foodExpPostDelete'],
    ],
    'GET_API' => [
        '/api/search' => ['ApiController', 'search'],
    ],
    'PATTERNS' => [
        'DELETE' => [
            '#^/api/reviews/(\d+)$#' => ['ApiController', 'reviewDeleteById'],
            '#^/api/restaurant-reviews/(\d+)$#' => ['ApiController', 'restaurantReviewDeleteById'],
        ],
    ],
];
